name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build and Deploy
        run: |
          npm ci
          npm run build
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" --exclude='.htaccess' ./build/ aakash@104.197.158.151:/var/www/html/red3-sixty/
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./build/.htaccess aakash@104.197.158.151:/var/www/html/red3-sixty/
