name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up SSH key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > key.pem
          chmod 600 key.pem
          mkdir -p ~/.ssh
          mv key.pem ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 104.197.158.151 >> ~/.ssh/known_hosts

      - name: Build and Deploy
        run: |
          npm ci
          npm run build
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" --exclude='.htaccess' ./build/ aakash@104.197.158.151:/var/www/html/red3-sixty/
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./build/.htaccess aakash@104.197.158.151:/var/www/html/red3-sixty/
