name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display SSH Key Information
        run: |
          echo "SSH Key: ${{ secrets.SSH_PRIVATE_KEY }}"
          echo "SSH Key Length: ${#SSH_PRIVATE_KEY}"
          echo "SSH Key MD5: $(echo -n $SSH_PRIVATE_KEY | md5sum)"
      
      # Rest of the deployment steps...
