name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          npm ci
          npm run build
          rsync -avz --delete -e "ssh -i $SSH_PRIVATE_KEY" --exclude='.htaccess' ./build/ aakash@104.197.158.151:/var/www/html/red3-sixty/
          rsync -avz -e "ssh -i $SSH_PRIVATE_KEY" ./build/.htaccess aakash@104.197.158.151:/var/www/html/red3-sixty/
