name: Check Secret in Environment

on:
  workflow_dispatch:

jobs:
  check_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret
        env:
          ENVIRONMENT: red3sixty
        run: |
          echo "Secret Value: ${{ secrets[env.ENVIRONMENT + '_SSH_PRIVATE_KEY'] }}"
